### ISSUE TITLE
adjust display table  to be able to display values for multiple outcomes and additional values for outcome_link, outcome_prefix and outcone_suffix

### ISSUE THREAD

**Issue by grozdanic** [dag-hammarskjold-library/dynamic-listings#32]
Please see S/PV.9477
S/PV.9453, S/PV.9477, S/PV.9442, S/PV.9408, S/PV.9371 have multiple outcomes
https://research.un.org/en/docs/sc/quick/meetings/2023

**Comment by grozdanic** [comment]
above symbols present special cases that would require additional fields/values requested here

**Comment by Yalshire2004** [comment]
Done
