### ISSUE TITLE
Add Refresh Table button

### ISSUE THREAD

**Issue by grozdanic** [dag-hammarskjold-library/dynamic-listings#33]
Add the red button to ‘Refresh Table’ next to the Blue button "Display Table". Clicking a button opens a dialog box to select the year and the month ( the default is the current year and current month). Click the refresh button in the dialog box to update the DL collection using the new module SC_meetings_outcomes.py in the GH repo.
![image](https://github.com/dag-hammarskjold-library/dynamic-listings/assets/46572480/1cba5dc7-44fc-40b0-b5ea-67106c851c2d)

**Comment by Yalshire2004** [comment]
@grozdanic please can you share with me the link of the GH repo?

**Comment by grozdanic** [comment]
it is in this repo...https://github.com/dag-hammarskjold-library/dynamic-listings/blob/main/dl/SC_Meetings_Outcomes.py

**Comment by Yalshire2004** [comment]
Thank you
